version: '3.7'

services:
  django_gunicorn:
    volumes:
      - static:/static
    env_file:
      - .env
    build:
      context: .
    ports:
      - "8000:8000"
  postgresql:
    image: postgres:15  # You can specify the PostgreSQL version you want here.
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  nginx:
    build: ./nginx
    volumes:
      - static:/static
      - ./ssl_key.key:/ssl_key.key
      - ./combined.crt:/combined.crt
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - django_gunicorn

volumes:
  static:
  postgres_data:  # Define a volume for PostgreSQL data persistence.
