version: '3.7'

services:
  django_gunicorn:
    volumes:
      - static:/static
    env_file:
      - .env
    build:
      context: .
    ports:
      - "8000:8000"
  nginx:
    build: ./nginx
    volumes:
      - static:/static
      - /combined.crt:/etc/nginx/combined.crt  
      - /ssl_key.key:/etc/nginx/ssl_key.key
      - /intermediate_pem_globalsign_ssl_dv_free_1.crt:/etc/nginx/intermediate_pem_globalsign_ssl_dv_free_1.crt
    ports:
      - "80:80"
    depends_on:
      - django_gunicorn

volumes:
  static: