version: '3.7'

services:
  django_gunicorn:
    volumes:
      - static:/static
    env_file:
      - .env
    build:
      context: .
    ports:
      - "8000:8000"
  postgresql:
    image: postgres:15
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    command: ["postgres", "-c", "listen_addresses=*", "-c", "password_encryption=scram-sha-256"]

  nginx:
    build: ./nginx
    volumes:
      - static:/static
      - ./www_school_broker_ru_2024_02_22.crt:/www_school_broker_ru_2024_02_22.crt  
      - ./ssl_key.key:/ssl_key.key
      - ./intermediate_pem_globalsign_ssl_dv_free_1.crt:/intermediate_pem_globalsign_ssl_dv_free_1.crt
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - django_gunicorn

volumes:
  static:
  postgres_data:  # Define a volume for PostgreSQL data persistence.
