# Generated by Django 4.2.3 on 2023-09-06 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_remove_course_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='continuation_day',
        ),
        migrations.AddField(
            model_name='course',
            name='continuation_day_1',
            field=models.CharField(blank=True, choices=[('Понедельник', 'Понедельник'), ('Вторник', 'Вторник'), ('Среда', 'Среда'), ('Четверг', 'Четверг'), ('Пятница', 'Пятница'), ('Суббота', 'Суббота'), ('Воскресенье', 'Воскресенье')], max_length=20, null=True, verbose_name='День продолжения курса 1'),
        ),
        migrations.AddField(
            model_name='course',
            name='continuation_day_2',
            field=models.CharField(blank=True, choices=[('Понедельник', 'Понедельник'), ('Вторник', 'Вторник'), ('Среда', 'Среда'), ('Четверг', 'Четверг'), ('Пятница', 'Пятница'), ('Суббота', 'Суббота'), ('Воскресенье', 'Воскресенье')], max_length=20, null=True, verbose_name='День продолжения курса 2'),
        ),
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.TextField(default=0, verbose_name='Описание курса'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=models.CharField(max_length=20, verbose_name='Продолжительность курса'),
        ),
    ]
