# Generated by Django 4.2.3 on 2023-10-31 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_remove_course_continuation_day_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={},
        ),
        migrations.RemoveField(
            model_name='course',
            name='continuation_day_1',
        ),
        migrations.RemoveField(
            model_name='course',
            name='continuation_day_2',
        ),
        migrations.RemoveField(
            model_name='course',
            name='continuation_time',
        ),
        migrations.RemoveField(
            model_name='course',
            name='day',
        ),
        migrations.RemoveField(
            model_name='course',
            name='description',
        ),
        migrations.RemoveField(
            model_name='course',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='course',
            name='enrolled_students_count',
        ),
        migrations.RemoveField(
            model_name='course',
            name='max_students',
        ),
        migrations.RemoveField(
            model_name='course',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='course',
            name='title',
        ),
    ]
