# Generated by Django 4.2.3 on 2023-10-31 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_course_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Course',
        ),
    ]
